// Dane menu Lupo: dania + składniki + tłumaczenia (UA / PL / EN).
// Ikony składników: assets/ingredients/*.svg (Twemoji 14.0.2, CC-BY 4.0 — patrz CREDITS.json).

export const CATS = [
  { key: 'antipasti', title: 'Antipasti', sub: 'Przystawki' },
  { key: 'pasta', title: 'Pasta', sub: 'Makarony' },
  { key: 'secondi', title: 'Secondi', sub: 'Dania główne' },
  { key: 'dolce', title: 'Dolce', sub: 'Desery' }
];

export const TIPS = [
  'Ucz się krótko, ale często — 15 minut trzy razy dziennie działa lepiej niż dwie godziny raz.',
  'Najpierw spróbuj przypomnieć sobie skład z pamięci, dopiero potem odsłoń odpowiedź.',
  'Wracaj do pozycji z sekcji „Do powtórzenia” — to Twoje słabe miejsca.',
  'Powtórz materiał wieczorem przed snem — sen pomaga utrwalić pamięć.',
  'Mów nazwy dań na głos — łatwiej je zapamiętasz i pewniej wymówisz gościom.',
  'Ucz się jednej kategorii na raz, potem mieszaj je w quizie i dopasowaniu.'
];

export const ING = {
  stracciatella: { it: 'stracciatella', uk: 'страчателла', pl: 'stracciatella (ser)', en: 'stracciatella cheese', icon: 'stracciatella.svg' },
  pomodorini: { it: 'pomodorini', uk: 'помідорчики черi', pl: 'pomidorki koktajlowe', en: 'cherry tomatoes', icon: 'pomodorini.svg' },
  pomodoro: { it: 'pomodoro', uk: 'помідор', pl: 'pomidor', en: 'tomato', icon: 'pomodorini.svg' },
  pomodorogiallo: { it: 'pomodoro giallo', uk: 'жовтий помідор', pl: 'żółty pomidor', en: 'yellow tomato', icon: 'pomodorini.svg' },
  basilico: { it: 'basilico', uk: 'базилік', pl: 'bazylia', en: 'basil', icon: 'basilico.svg' },
  erbe: { it: 'erbe', uk: 'трави', pl: 'zioła', en: 'herbs', icon: 'basilico.svg' },
  alloro: { it: 'alloro', uk: 'лавровий лист', pl: 'liść laurowy', en: 'bay leaf', icon: 'basilico.svg' },
  olio: { it: 'olio d’oliva', uk: 'оливкова олія', pl: 'oliwa z oliwek', en: 'olive oil', icon: 'olio-oliva.svg' },
  olive: { it: 'olive', uk: 'оливки', pl: 'oliwki', en: 'olives', icon: 'olio-oliva.svg' },
  pastafresca: { it: 'pasta fresca', uk: 'свіжа паста', pl: 'świeży makaron', en: 'fresh pasta', icon: 'pasta-fresca.svg' },
  ricotta: { it: 'ricotta', uk: 'рікота', pl: 'ricotta (ser)', en: 'ricotta cheese', icon: 'ricotta.svg' },
  parmigiano: { it: 'parmigiano', uk: 'пармезан', pl: 'parmezan', en: 'parmesan', icon: 'parmigiano.svg' },
  pecorino: { it: 'pecorino', uk: 'пекоріно', pl: 'pecorino', en: 'pecorino cheese', icon: 'parmigiano.svg' },
  spinaci: { it: 'spinaci', uk: 'шпинат', pl: 'szpinak', en: 'spinach', icon: 'spinaci.svg' },
  crescione: { it: 'crescione', uk: 'крес-салат', pl: 'rukiew wodna', en: 'watercress', icon: 'spinaci.svg' },
  burro: { it: 'burro', uk: 'вершкове масло', pl: 'masło', en: 'butter', icon: 'burro.svg' },
  mascarpone: { it: 'mascarpone', uk: 'маскарпоне', pl: 'mascarpone (ser)', en: 'mascarpone cheese', icon: 'mascarpone.svg' },
  caffe: { it: 'caffè', uk: 'кава (еспресо)', pl: 'kawa (espresso)', en: 'coffee (espresso)', icon: 'caffe.svg' },
  savoiardi: { it: 'savoiardi', uk: '«дамські пальчики»', pl: 'biszkopty savoiardi', en: 'ladyfinger biscuits', icon: 'savoiardi.svg' },
  cacao: { it: 'cacao', uk: 'какао-порошок', pl: 'kakao w proszku', en: 'cocoa powder', icon: 'cacao.svg' },
  cioccolato: { it: 'cioccolato', uk: 'шоколад', pl: 'czekolada', en: 'chocolate', icon: 'cacao.svg' },
  uova: { it: 'uova', uk: 'яйця', pl: 'jajka', en: 'eggs', icon: 'uova.svg' },
  tuorlo: { it: 'tuorlo', uk: 'жовток', pl: 'żółtko', en: 'egg yolk', icon: 'uova.svg' },
  salvia: { it: 'salvia', uk: 'шавлія', pl: 'szałwia', en: 'sage', icon: 'salvia.svg' },
  farina: { it: 'farina', uk: 'борошно', pl: 'mąka', en: 'flour', icon: 'farina.svg' },
  lievito: { it: 'lievito', uk: 'дріжджі', pl: 'drożdże', en: 'yeast', icon: 'lievito.svg' },
  cipolla: { it: 'cipolla', uk: 'цибуля-шалот', pl: 'szalotka', en: 'shallot', icon: 'cipolla.svg' },
  porro: { it: 'porro', uk: 'порей', pl: 'por', en: 'leek', icon: 'cipolla.svg' },
  aceto: { it: 'aceto', uk: 'оцет', pl: 'ocet', en: 'vinegar', icon: 'aceto.svg' },
  vermut: { it: 'vermut', uk: 'вермут', pl: 'wermut', en: 'vermouth', icon: 'aceto.svg' },
  coriandolo: { it: 'coriandolo', uk: 'коріандр', pl: 'kolendra', en: 'coriander', icon: 'coriandolo.svg' },
  rabarbaro: { it: 'rabarbaro', uk: 'ревінь', pl: 'rabarbar', en: 'rhubarb', icon: 'coriandolo.svg' },
  arancia: { it: 'arancia', uk: 'апельсин', pl: 'pomarańcza', en: 'orange', icon: 'arancia.svg' },
  insalata: { it: 'insalata', uk: 'салат', pl: 'sałata', en: 'lettuce', icon: 'insalata.svg' },
  fagiolini: { it: 'fagiolini', uk: 'спаржева квасоля', pl: 'fasolka szparagowa', en: 'green beans', icon: 'fave.svg' },
  fave: { it: 'fave', uk: 'боби', pl: 'bób', en: 'fava beans', icon: 'fave.svg' },
  capperi: { it: 'capperi', uk: 'каперси', pl: 'kapary', en: 'capers', icon: 'fave.svg' },
  pesca: { it: 'pesca', uk: 'персик', pl: 'brzoskwinia', en: 'peach', icon: 'pesca.svg' },
  mandorla: { it: 'mandorla', uk: 'мигдаль', pl: 'migdał', en: 'almond', icon: 'mandorla.svg' },
  verbena: { it: 'verbena', uk: 'вербена', pl: 'werbena', en: 'verbena', icon: 'verbena.svg' },
  orata: { it: 'orata', uk: 'дорада', pl: 'dorada', en: 'sea bream', icon: 'orata.svg' },
  finocchio: { it: 'finocchio', uk: 'фенхель', pl: 'koper włoski', en: 'fennel', icon: 'finocchio.svg' },
  uvaspina: { it: 'uva spina', uk: 'агрус', pl: 'agrest', en: 'gooseberry', icon: 'uvaspina.svg' },
  pane: { it: 'pane', uk: 'хліб', pl: 'chleb', en: 'bread', icon: 'pane.svg' },
  brioche: { it: 'brioche', uk: 'здобна булочка', pl: 'bułka drożdżowa', en: 'brioche bun', icon: 'pane.svg' },
  fioridizucca: { it: 'fiori di zucca', uk: 'квіти цукіні', pl: 'kwiaty cukinii', en: 'zucchini flowers', icon: 'fioridizucca.svg' },
  formaggiocapra: { it: 'formaggio di capra', uk: 'козячий сир', pl: 'ser kozi', en: 'goat cheese', icon: 'formaggiocapra.svg' },
  manzo: { it: 'manzo', uk: 'яловичина', pl: 'wołowina', en: 'beef', icon: 'manzo.svg' },
  guanciadimanzo: { it: 'guancia di manzo', uk: 'яловича щока', pl: 'policzek wołowy', en: 'beef cheek', icon: 'manzo.svg' },
  funghi: { it: 'funghi', uk: 'гриби', pl: 'grzyby', en: 'mushrooms', icon: 'funghi.svg' },
  gallinacci: { it: 'gallinacci', uk: 'лисички', pl: 'kurki', en: 'chanterelle mushrooms', icon: 'funghi.svg' },
  verdure: { it: 'verdure', uk: 'овочі', pl: 'warzywa', en: 'vegetables', icon: 'verdure.svg' },
  gnocchi: { it: 'gnocchi', uk: 'ньокі', pl: 'gnocchi', en: 'gnocchi', icon: 'patate.svg' },
  patate: { it: 'patate', uk: 'картопля', pl: 'ziemniaki', en: 'potatoes', icon: 'patate.svg' },
  zafferano: { it: 'zafferano', uk: 'шафран', pl: 'szafran', en: 'saffron', icon: 'zafferano.svg' },
  zucchine: { it: 'zucchine', uk: 'цукіні', pl: 'cukinia', en: 'zucchini', icon: 'zucchine.svg' },
  salsiccia: { it: 'salsiccia', uk: 'ковбаса', pl: 'kiełbasa', en: 'sausage', icon: 'salsiccia.svg' },
  gamberi: { it: 'gamberi', uk: 'креветки', pl: 'krewetki', en: 'shrimp', icon: 'gamberi.svg' },
  limone: { it: 'limone', uk: 'лимон', pl: 'cytryna', en: 'lemon', icon: 'limone.svg' },
  limoncello: { it: 'limoncello', uk: 'лимончело', pl: 'limoncello', en: 'limoncello', icon: 'limone.svg' },
  astice: { it: 'astice', uk: 'омар', pl: 'homar', en: 'lobster', icon: 'astice.svg' },
  guanciale: { it: 'guanciale', uk: 'гуанчале', pl: 'guanciale', en: 'cured pork cheek', icon: 'guanciale.svg' },
  melanzana: { it: 'melanzana', uk: 'баклажан', pl: 'bakłażan', en: 'eggplant', icon: 'melanzana.svg' },
  cozze: { it: 'cozze', uk: 'мідії', pl: 'małże', en: 'mussels', icon: 'cozze.svg' },
  maiale: { it: 'maiale', uk: 'свинина', pl: 'wieprzowina', en: 'pork', icon: 'maiale.svg' },
  pepeverde: { it: 'pepe verde', uk: 'зелений перець', pl: 'zielony pieprz', en: 'green pepper', icon: 'pepeverde.svg' },
  yogurt: { it: 'yogurt', uk: 'йогурт', pl: 'jogurt', en: 'yogurt', icon: 'yogurt.svg' },
  panna: { it: 'panna', uk: 'вершки', pl: 'śmietana', en: 'cream', icon: 'yogurt.svg' },
  lamponi: { it: 'lamponi', uk: 'малина', pl: 'maliny', en: 'raspberries', icon: 'lamponi.svg' },
  melone: { it: 'melone', uk: 'диня', pl: 'melon', en: 'melon', icon: 'melone.svg' },
  stracchino: { it: 'stracchino', uk: 'страккіно', pl: 'stracchino (ser)', en: 'stracchino cheese', icon: 'stracciatella.svg' },
  nocciole: { it: 'nocciole', uk: 'фундук', pl: 'orzechy laskowe', en: 'hazelnuts', icon: 'nocciole.svg' },
  mirtilli: { it: 'mirtilli', uk: 'чорниця', pl: 'jagody', en: 'blueberries', icon: 'mirtilli.svg' },
  camomilla: { it: 'camomilla', uk: 'ромашка', pl: 'rumianek', en: 'chamomile', icon: 'camomilla.svg' },
  pastachoux: { it: 'pasta choux', uk: 'заварне тісто', pl: 'ciasto choux', en: 'choux pastry', icon: 'pastachoux.svg' },
  zucchero: { it: 'zucchero', uk: 'цукор', pl: 'cukier', en: 'sugar', icon: 'zucchero.svg' },
  vodka: { it: 'vodka', uk: 'горілка', pl: 'wódka', en: 'vodka', icon: 'vodka.svg' }
};

export const ITEMS = [
  { id: 'a1', cat: 'antipasti', name: 'salvia fritta', pron: 'salwia fritta', desc: 'chrupiące liście szałwii', price: '12', veg: 'v',
    ingIds: ['salvia', 'farina', 'olio'],
    tr: { name: { uk: 'Смажена шавлія', pl: 'Smażona szałwia', en: 'Fried sage' }, desc: { uk: 'хрусткі листки шавлії', en: 'crispy sage leaves' } } },
  { id: 'a2', cat: 'antipasti', name: 'cipolline sottaceti', pron: 'czipolline sottaczeti', desc: 'piklowane szalotki w occie z czerwonego wina i ziarnami kolendry', price: '12', veg: 'vg',
    ingIds: ['cipolla', 'aceto', 'coriandolo'],
    tr: { name: { uk: 'Мариновані цибулини', pl: 'Marynowane cebulki', en: 'Pickled baby onions' }, desc: { uk: 'мариновані шалот в оцті з червоного вина з насінням коріандру', en: 'shallots pickled in red-wine vinegar with coriander seeds' } } },
  { id: 'a3', cat: 'antipasti', name: 'olive verdi', pron: 'olive werdi', desc: 'marynowane oliwki „Castelvetrano” z liściem laurowym i skórką z pomarańczy', price: '12', veg: 'vg',
    ingIds: ['olive', 'alloro', 'arancia'],
    tr: { name: { uk: 'Зелені оливки', pl: 'Zielone oliwki', en: 'Green olives' }, desc: { uk: 'мариновані оливки «Кастельветрано» з лавровим листям і апельсиновою цедрою', en: 'marinated Castelvetrano olives with bay leaf and orange zest' } } },
  { id: 'a4', cat: 'antipasti', name: 'antipasti misti', pron: 'antipasti misti', desc: 'zestaw: piklowane szalotki, oliwki, liście szałwii', price: '33', veg: 'vg',
    ingIds: ['cipolla', 'olive', 'salvia'],
    tr: { name: { uk: 'Асорті закусок', pl: 'Zestaw przystawek', en: 'Mixed antipasti' }, desc: { uk: 'асорті: мариновані шалот, оливки, листя шавлії', en: 'a set of pickled shallots, olives and sage leaves' } } },
  { id: 'a5', cat: 'antipasti', name: 'focaccia', pron: 'fokacza', desc: 'domowa focaccia z oliwą z oliwek', price: '12', veg: 'vg',
    ingIds: ['farina', 'olio', 'lievito'],
    tr: { name: { uk: 'Фокачча', pl: 'Focaccia', en: 'Focaccia' }, desc: { uk: 'домашня фокачча з оливковою олією', en: 'homemade focaccia with olive oil' } } },
  { id: 'a6', cat: 'antipasti', name: 'insalata verde', pron: 'insalata werde', desc: 'mieszanka sezonowych sałat i ziół', price: '18', veg: 'vg',
    ingIds: ['insalata', 'erbe'],
    tr: { name: { uk: 'Зелений салат', pl: 'Zielona sałatka', en: 'Green salad' }, desc: { uk: 'суміш сезонних салатів і трав', en: 'a mix of seasonal greens and herbs' } } },
  { id: 'a7', cat: 'antipasti', name: 'caprese diversa', pron: 'kaprese diwersa', desc: 'kremowy ser stracciatella z karmelizowanymi pomidorami i oliwą bazyliową', price: '42', veg: 'v',
    ingIds: ['stracciatella', 'pomodorini', 'basilico', 'olio'],
    tr: { name: { uk: 'Інша капрезе', pl: 'Inna caprese', en: 'A different caprese' }, desc: { uk: 'вершковий сир страчателла з карамелізованими помідорами та базиліковою олією', en: 'creamy stracciatella cheese with caramelized tomatoes and basil oil' } } },
  { id: 'a8', cat: 'antipasti', name: 'fagiolini con pesche', pron: 'fadżolini kon peske', desc: 'żółta fasolka szparagowa ze świeżymi brzoskwiniami, migdałami i werbeną', price: '32', veg: 'vg',
    ingIds: ['fagiolini', 'pesca', 'mandorla', 'verbena'],
    tr: { name: { uk: 'Квасоля з персиками', pl: 'Fasolka z brzoskwiniami', en: 'Green beans with peaches' }, desc: { uk: 'жовта спаржева квасоля зі свіжими персиками, мигдалем і вербеною', en: 'yellow green beans with fresh peaches, almonds and verbena' } } },
  { id: 'a9', cat: 'antipasti', name: 'crudo di orata con crema di finocchio', pron: 'krudo di orata kon krema di finokkio', desc: 'crudo z dorady z kremem z kopru włoskiego, agrestem, kaparami z czosnku niedźwiedziego i chrupiącym chlebem sardyńskim', price: '48', veg: null,
    ingIds: ['orata', 'finocchio', 'uvaspina', 'pane'],
    tr: { name: { uk: 'Крудо з дорадо', pl: 'Crudo z doradą', en: 'Sea bream crudo' }, desc: { uk: 'крудо з дорадо з кремом з фенхелю, агрусом, каперсами з ведмежої цибулі та хрустким сардинським хлібом', en: 'sea bream crudo with fennel cream, gooseberry, wild-garlic capers and crispy Sardinian bread' } } },
  { id: 'a10', cat: 'antipasti', name: 'fiori di zucca con pappa al pomodoro', pron: 'fiori di dzukka kon pappa al pomodoro', desc: 'smażone kwiaty cukinii z serem kozim i bobem, tymiankiem, chili i chłodnikiem ze świeżych pomidorów', price: '48', veg: 'v',
    ingIds: ['fioridizucca', 'formaggiocapra', 'fave', 'pomodoro'],
    tr: { name: { uk: 'Квіти цукіні', pl: 'Kwiaty cukinii', en: 'Zucchini flowers' }, desc: { uk: 'смажені квіти цукіні з козячим сиром і бобами, чебрецем, чилі та холодним супом зі свіжих помідорів', en: 'fried zucchini flowers with goat cheese, fava beans, thyme, chili and cold fresh-tomato soup' } } },
  { id: 'a11', cat: 'antipasti', name: 'tartare al parmigiano', pron: 'tartare al parmidżano', desc: 'tatar wołowy z żółtkiem przepiórczym, pianką parmezanową i marynowanymi opieńkami', price: '52', veg: null,
    ingIds: ['manzo', 'tuorlo', 'parmigiano', 'funghi'],
    tr: { name: { uk: 'Тартар з пармезаном', pl: 'Tatar z parmezanem', en: 'Beef tartare with parmesan' }, desc: { uk: 'яловичий тартар з перепелиним жовтком, пармезановою піною та маринованими опеньками', en: 'beef tartare with quail egg yolk, parmesan foam and marinated honey mushrooms' } } },
  { id: 'a12', cat: 'antipasti', name: 'zuppa del giorno', pron: 'dzuppa del dżorno', desc: 'zupa dnia', price: '18', veg: null,
    ingIds: ['verdure'],
    tr: { name: { uk: 'Суп дня', pl: 'Zupa dnia', en: 'Soup of the day' }, desc: { uk: 'суп дня', en: 'soup of the day' } } },

  { id: 'p1', cat: 'pasta', name: 'occhi di lupo alla vodka', pron: 'okki di lupo alla wodka', desc: 'klasyk lat 80-tych, sos śmietanowo-pomidorowy z dodatkiem wódki', price: '32', veg: 'v',
    ingIds: ['pastafresca', 'pomodoro', 'panna', 'vodka'],
    tr: { name: { uk: '«Вовчі очі» з горілкою', pl: 'Occhi di lupo z wódką', en: '"Wolf\'s eyes" pasta with vodka' }, desc: { uk: 'класика 80-х, вершково-томатний соус з горілкою', en: 'an 80s classic — creamy tomato sauce with a splash of vodka' } } },
  { id: 'p2', cat: 'pasta', name: 'rosette al ragù', pron: 'rozette al ragu', desc: 'rodzaj lasagne z Modeny z długo gotowanymi policzkami wołowymi po bolońsku z ziołami', price: '48', veg: null,
    ingIds: ['pastafresca', 'guanciadimanzo', 'erbe'],
    tr: { name: { uk: 'Розетки з рагу', pl: 'Rosette z ragù', en: 'Rosette pasta with ragù' }, desc: { uk: 'різновид лазаньї з Модени з довго тушкованими яловичими щоками по-болонськи з травами', en: 'a Modena-style lasagne roll with slow-cooked Bolognese beef cheek and herbs' } } },
  { id: 'p3', cat: 'pasta', name: 'gnocchi allo zafferano e zucchine novelle', pron: 'niokki allo dzafferano e dzukkine nowelle', desc: 'gnocchi ze słodkich ziemniaków z szafranem w sosie z żółtych pomidorów, z młodymi cukiniami i ziołami', price: '46', veg: null,
    ingIds: ['gnocchi', 'zafferano', 'zucchine', 'pomodorogiallo'],
    tr: { name: { uk: 'Ньокі з шафраном', pl: 'Gnocchi z szafranem', en: 'Saffron gnocchi' }, desc: { uk: 'ньокі з батату з шафраном у соусі з жовтих помідорів, з молодими цукіні та травами', en: 'sweet-potato saffron gnocchi in yellow-tomato sauce with baby zucchini and herbs' } } },
  { id: 'p4', cat: 'pasta', name: 'fazzoletti con gallinacci', pron: 'faccoletti kon gallinaczi', desc: 'płat świeżego makaronu z kurkami, płynnym żółtkiem confit, majerankiem i z pesto z rukwi wodnej', price: '60', veg: 'v',
    ingIds: ['pastafresca', 'gallinacci', 'tuorlo', 'crescione'],
    tr: { name: { uk: '«Хустинки» з лисичками', pl: 'Fazzoletti z kurkami', en: '"Handkerchief" pasta with chanterelles' }, desc: { uk: 'пласт свіжої пасти з лисичками, рідким жовтком конфі, майораном і песто з крес-салату', en: 'a sheet of fresh pasta with chanterelles, confit egg yolk, marjoram and watercress pesto' } } },
  { id: 'p5', cat: 'pasta', name: 'casarecce con salsiccia', pron: 'kazarecze kon salsiczcza', desc: 'krótki makaron z Sycylii, z włoską kiełbasą salsiccia fresca, pieczonym fenkułem i skórką z pomarańczy', price: '46', veg: null,
    ingIds: ['pastafresca', 'salsiccia', 'finocchio', 'arancia'],
    tr: { name: { uk: 'Казаречче з ковбаскою', pl: 'Casarecce z kiełbasą', en: 'Casarecce with sausage' }, desc: { uk: 'короткий макарон з Сицилії з італійською ковбаскою салсіча, печеним фенхелем і апельсиновою цедрою', en: 'short Sicilian pasta with fresh Italian sausage, roasted fennel and orange zest' } } },
  { id: 'p6', cat: 'pasta', name: 'fiori', pron: 'fiori', desc: 'makaron nadziewany ricottą, parmezanem, mascarpone, szpinakiem i oregano, z palonym masłem', price: '44', veg: 'v',
    ingIds: ['pastafresca', 'ricotta', 'parmigiano', 'spinaci', 'burro'],
    tr: { name: { uk: 'Квіти (фарширована паста)', pl: 'Kwiaty (nadziewany makaron)', en: 'Flowers (stuffed pasta)' }, desc: { uk: 'паста, начинена рікотою, пармезаном, маскарпоне, шпинатом та орегано, з пряженим маслом', en: 'pasta stuffed with ricotta, parmesan, mascarpone, spinach and oregano, with browned butter' } } },
  { id: 'p7', cat: 'pasta', name: 'lasagnette alfredo', pron: 'lazaniette alfredo', desc: 'pasy makaronu z krewetkami, cytryną confit, masłem i parmezanem', price: '58', veg: null,
    ingIds: ['pastafresca', 'gamberi', 'limone', 'burro', 'parmigiano'],
    tr: { name: { uk: 'Лазаньєтте альфредо', pl: 'Lasagnette alfredo', en: 'Lasagnette Alfredo' }, desc: { uk: 'смужки пасти з креветками, цитриною конфі, вершковим маслом і пармезаном', en: 'pasta ribbons with shrimp, confit lemon, butter and parmesan' } } },
  { id: 'p8', cat: 'pasta', name: 'spaghetti alla chitarra con astice', pron: 'spagetti alla kitarra kon asticze', desc: 'spaghetti z homarem, żółtymi pomidorami, papryką goccia, kolendrą i cytrynowym pangrattato', price: '98', veg: null,
    ingIds: ['pastafresca', 'astice', 'pomodorogiallo', 'coriandolo'],
    tr: { name: { uk: 'Спагеті з омаром', pl: 'Spaghetti z homarem', en: 'Spaghetti with lobster' }, desc: { uk: 'спагеті аль-кітарра з омаром, жовтими помідорами, перцем гоччіа, коріандром і лимонним панграттато', en: 'guitar-cut spaghetti with lobster, yellow tomatoes, goccia pepper, coriander and lemon breadcrumbs' } } },
  { id: 'p9', cat: 'pasta', name: 'spaghettoni alla carbonara', pron: 'spagettoni alla karbonara', desc: 'spaghettoni z guanciale, serem pecorino i jajkiem konfitowanym (możliwa zamiana na spaghetti bezglutenowe)', price: '48', veg: null,
    ingIds: ['pastafresca', 'guanciale', 'pecorino', 'uova'],
    tr: { name: { uk: 'Спагеттоні карбонара', pl: 'Spaghettoni carbonara', en: 'Spaghettoni carbonara' }, desc: { uk: 'спагеттоні з гуанчале, сиром пекоріно і конфітованим яйцем', en: 'spaghettoni with guanciale, pecorino cheese and confit egg (gluten-free spaghetti available)' } } },

  { id: 's1', cat: 'secondi', name: 'melanzane e parmigiano', pron: 'melandzane e parmidżano', desc: 'pieczony bakłażan z kremem parmezanowym, pomidorkami i perełkami parmezanowymi', price: '52', veg: 'v',
    ingIds: ['melanzana', 'parmigiano', 'pomodorini'],
    tr: { name: { uk: 'Баклажан з пармезаном', pl: 'Bakłażan z parmezanem', en: 'Eggplant parmesan' }, desc: { uk: 'печений баклажан з пармезановим кремом, помідорчиками і пармезановими перлинами', en: 'roasted eggplant with parmesan cream, cherry tomatoes and parmesan pearls' } } },
  { id: 's2', cat: 'secondi', name: 'filetto di orata con porri novelli', pron: 'filetto di orata kon porri nowelli', desc: 'filet z dorady z młodymi porami i ziemniakami, mulami, sosem maślanym z wermutem i kaparami', price: '98', veg: null,
    ingIds: ['orata', 'porro', 'cozze', 'burro'],
    tr: { name: { uk: 'Філе дорадо з пореєм', pl: 'Filet z dorady z porami', en: 'Sea bream fillet with leeks' }, desc: { uk: 'філе дорадо з молодим пореєм і картоплею, мідіями, вершковим соусом з вермутом і каперсами', en: 'sea bream fillet with baby leeks and potatoes, mussels, and a vermouth butter-caper sauce' } } },
  { id: 's3', cat: 'secondi', name: 'cotoletta alla milanese', pron: 'kotoletta alla milaneze', desc: 'mediolański schab z kością, z kremem parmezanowym, sezonowymi sałatami i młodymi ziemniakami', price: '66', veg: null,
    ingIds: ['maiale', 'parmigiano', 'insalata', 'patate'],
    tr: { name: { uk: 'Котлета по-міланськи', pl: 'Kotlet po mediolańsku', en: 'Milanese cutlet' }, desc: { uk: 'міланська свиняча котлета на кістці з пармезановим кремом, сезонними салатами і молодою картоплею', en: 'bone-in Milanese-style pork cutlet with parmesan cream, seasonal greens and baby potatoes' } } },
  { id: 's4', cat: 'secondi', name: 'filetto di manzo', pron: 'filetto di mandzo', desc: 'stek z polędwicy wołowej z sosem z zielonego pieprzu, sałatką z cukinii i ziemniaczano-cytrynowym puree', price: '124', veg: null,
    ingIds: ['manzo', 'pepeverde', 'zucchine', 'patate'],
    tr: { name: { uk: 'Яловичий філей', pl: 'Polędwica wołowa', en: 'Beef fillet' }, desc: { uk: 'стейк з яловичої вирізки з соусом із зеленого перцю, салатом з цукіні та картопляно-лимонним пюре', en: 'beef tenderloin steak with green-peppercorn sauce, zucchini salad and lemon-potato purée' } } },

  { id: 'd1', cat: 'dolce', name: 'gelato allo yogurt e lamponi con melone', pron: 'dżelato allo jogurt e lamponi kon melone', desc: 'jogurtowo-malinowe lody soft serve z melonem, oliwą z oliwek i kwiatem czarnego bzu', price: '22', veg: null,
    ingIds: ['yogurt', 'lamponi', 'melone'],
    tr: { name: { uk: 'Йогуртове морозиво з малиною', pl: 'Lody jogurtowe z malinami', en: 'Yogurt-raspberry gelato' }, desc: { uk: 'йогуртово-малинове морозиво софт з динею, оливковою олією і квіткою бузини', en: 'yogurt-raspberry soft-serve with melon, olive oil and elderflower' } } },
  { id: 'd2', cat: 'dolce', name: 'torta di stracchino con lamponi', pron: 'torta di strakkino kon lamponi', desc: 'kremowe ciastko z włoskiego sera Stracchino, z orzechowo-słonym spodem i świeżymi malinami', price: '24', veg: null,
    ingIds: ['stracchino', 'lamponi', 'nocciole'],
    tr: { name: { uk: 'Тортик зі страккіно', pl: 'Ciastko ze stracchino', en: 'Stracchino cake' }, desc: { uk: 'кремовий тортик з італійського сиру страккіно, з горіхово-солоною основою і свіжою малиною', en: 'creamy Italian stracchino-cheese cake with a salted-nut base and fresh raspberries' } } },
  { id: 'd3', cat: 'dolce', name: 'maritozzo con la panna e mirtilli', pron: 'maritocco kon la panna e mirtilli', desc: 'rzymska bułeczka z bitą śmietaną i świeżymi jagodami', price: '22', veg: null,
    ingIds: ['brioche', 'panna', 'mirtilli'],
    tr: { name: { uk: 'Марітоццо з вершками', pl: 'Maritozzo ze śmietaną', en: 'Maritozzo with cream' }, desc: { uk: 'римська булочка зі збитими вершками і свіжою чорницею', en: 'Roman bun with whipped cream and fresh blueberries' } } },
  { id: 'd4', cat: 'dolce', name: 'panna cotta alla camomilla con rabarbaro', pron: 'panna kotta alla kamomilla kon rabarbaro', desc: 'rumiankowa panna cotta z rabarbarem i oliwą z oliwek', price: '20', veg: null,
    ingIds: ['panna', 'camomilla', 'rabarbaro'],
    tr: { name: { uk: 'Панна-котта з ромашкою', pl: 'Panna cotta z rumiankiem', en: 'Chamomile panna cotta' }, desc: { uk: 'ромашкова панна-котта з ревенем і оливковою олією', en: 'chamomile panna cotta with rhubarb and olive oil' } } },
  { id: 'd5', cat: 'dolce', name: 'profiterole', pron: 'profiterole', desc: 'ciasto „choux” z waniliową bitą śmietaną i czekoladą', price: '22', veg: null,
    ingIds: ['pastachoux', 'panna', 'cioccolato'],
    tr: { name: { uk: 'Профітролі', pl: 'Profiterolki', en: 'Profiteroles' }, desc: { uk: 'заварне тісто з ванільними збитими вершками і шоколадом', en: 'choux pastry with vanilla whipped cream and chocolate' } } },
  { id: 'd6', cat: 'dolce', name: 'granita siciliana', pron: 'granita siczyliana', desc: 'cytrynowa granita z bazylią (0%) lub cytrynowa granita z limoncello', price: '18/26', veg: null,
    ingIds: ['limone', 'basilico', 'limoncello'],
    tr: { name: { uk: 'Сицилійська граніта', pl: 'Granita sycylijska', en: 'Sicilian granita' }, desc: { uk: 'лимонна граніта з базиліком (0%) або лимонна граніта з лимончело', en: 'lemon granita with basil (0% alcohol) or lemon granita with limoncello' } } },
  { id: 'd7', cat: 'dolce', name: 'tiramisù', pron: 'tiramisu', desc: 'klasyczne tiramisù z kremem mascarpone, biszkoptami savoiardi nasączonymi espresso i kakao', price: '22', veg: null,
    ingIds: ['mascarpone', 'caffe', 'savoiardi', 'cacao', 'uova'],
    tr: { name: { uk: 'Тірамісу («підніми мене»)', pl: 'Tiramisù (dosłownie „podnieś mnie”)', en: 'Tiramisu (literally "pick me up")' }, desc: { uk: 'класичний тірамісу: крем маскарпоне, савоярді, просочені еспресо, і какао', en: 'classic tiramisù: mascarpone cream, savoiardi biscuits soaked in espresso, and cocoa' } } },
  { id: 'd8', cat: 'dolce', name: 'sorbetto al limone', pron: 'sorbetto al limone', desc: 'sorbet cytrynowy', price: '14', veg: null,
    ingIds: ['limone', 'zucchero'],
    tr: { name: { uk: 'Лимонний сорбет', pl: 'Sorbet cytrynowy', en: 'Lemon sorbet' }, desc: { uk: 'лимонний сорбет', en: 'lemon sorbet' } } }
];
